config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'colors/index'
  get 'colors/trend'

  resources :colors do
  	member do
  		get :vote_up
  	end
  end

  root 'colors#index'

  get '*path' => redirect('/') #redirect to home other pages
end

app/models/color.rb
class Color < ActiveRecord::Base
	acts_as_voteable
	validates :color1, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	# Removed User sign up...
	# devise :database_authenticatable, :registerable,
	#      :recoverable, :rememberable, :trackable, :validatable

	devise :database_authenticatable, 
			:rememberable, :trackable, :validatable

	acts_as_voter
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, lambda { order("created_at DESC") }

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable if ActiveRecord::VERSION::MAJOR < 4


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
	before_action :find_color, only: [:show, :edit, :update, :destroy, :vote_up]
	before_action :authenticate_user!, except: [:index, :show, :trend, :vote_up]
	before_action :admin_user_logged?, only: [:edit, :update, :destroy]
	before_action :voteup_time, only: [:vote_up]

	def index
		@colors = Color.all.order("created_at desc")		
	end	

	def new
		@color = Color.new
	end

	def create
		@color = Color.new color_params

		if @color.save
			redirect_to @color, notice: "Nice Cool Color! It was successfully created"
		else
			render 'new', notice: "Oh no! Could you try again?"
		end

	end

	def show
	end

	def edit
	end

	def update
		if @color.update color_params
			redirect_to @color, notice: "Yeah! Updated!"
		else		
			render 'edit'
		end
	end

	def destroy
		@color.destroy
		redirect_to colors_path, notice: "Color deleted... You're right, that wasn't so cool!"
	end

	def vote_up
		@current_user = User.first
		if @color.update_attributes(:updated_at => DateTime.now)
			begin
				current_user.vote_for(@color)
				redirect_to :back, notice: "Thanks for voting"
			rescue ActionController::RedirectBackError
				redirect_to root_path
			end			
		end
	end

	def trend
		@colors = Color.plusminus_tally.order('plusminus_tally DESC')	
	end	

	private

	def color_params
		params.require(:color).permit(:color1, :color2, :color3)
	end

	def find_color
		@color = Color.find(params[:id])		
	end

	def admin_user_logged?
		if current_user.admin?
		else
			redirect_to root_path
		end
	end

	def voteup_time
		old_date = @color.updated_at_was
		if old_date > (DateTime.now - 1.minutes)
			redirect_to :back, notice: "You already voted!"
		end
		rescue ActionController::RedirectBackError
  		redirect_to root_path		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/views/colors/_form.html.erb
<div class="form-control new-color">
	<%= form_for @color do |f| %>
		<% if @color.errors.any? %>
		<h2><%= pluralize(@color.errors.count, "error") %> prevented this post from saving:</h2>
		<ul>
			<%= @color.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
		<% end %>
		<div class="field">
		<%= f.label :color1 %><br>
		<%= f.text_field :color1 %>
			
		</div>
		<div class="field">
		<%= f.label :color2 %><br>
		<%= f.text_field :color2 %>
			
		</div>
		<div class="field">
		<%= f.label :color3 %><br>
		<%= f.text_field :color3 %>
		</div>
		<div class="actions">
		<%= f.submit :class => 'btn btn-primary btn-lg btn-block' %>
		</div>

	<% end %>
</div>

app/views/colors/edit.html.erb
<div class="row">
	<div class="forms">
		
		<h2>Edit Color</h2>
		<%= render 'form' %>
	</div>
</div>

app/views/colors/index.html.erb
<div id="colors-wrapper" class="row">

	<div class="menu-options clearfix">
		<ul class="col-xs-12">
			<li>
				<%= link_to "latest", root_path, class: "latest active" %>
			</li>
			<li>
				<%= link_to "trends", colors_trend_path, class: "trend" %>
			</li>
		</ul>
	</div>

<% @colors.each do |color| %>
	<div id="color-<%= color.id %>" class="col-xs-12 col-sm-6 col-md-4 col-lg-3 box-color">
		<button class="btn" data-clipboard-text="<%= color.color1 %>" ><i class="ion-waterdrop color-drop" style="color: <%= color.color1 %>"></i></button><br>
		<button class="btn" data-clipboard-text="<%= color.color2 %>" ><i class="ion-waterdrop color-drop" style="color: <%= color.color2 %>"></i></button><br>
		<button class="btn" data-clipboard-text="<%= color.color3 %>" ><i class="ion-waterdrop color-drop" style="color: <%= color.color3 %>"></i></button><br>		

		<ul class="list">
			<li>
				<%= link_to vote_up_color_path(color), class: "likes" do %>
					<i class="icon ion-heart"></i><%= color.votes_for %>
				<% end %>				
			</li>
			<li><%= link_to 'Show Coolor', color, :class => "show" %></li>
		</ul>
		
	</div>
<% end %>
</div>
<%= javascript_tag do %>
	var clipboard = new Clipboard('.btn');
	clipboard.on('success', function(e) {
	console.log(e);
	});
	clipboard.on('error', function(e) {
	console.log(e);
	});
<% end %>

app/views/colors/new.html.erb
<div class="row">
	<div class="forms">
		
		<h2>New Color</h2>
		<%= render 'form' %>
	</div>
</div>

app/views/colors/show.html.erb
<div id="colors-wrapper" class="row">
	<div id="color-id-showpage-<%= @color.id %>" class="col-sm-12 show-page" >
		<button class="btn" data-clipboard-text="<%= @color.color1 %>" ><i class="ion-waterdrop color-drop" style="color: <%= @color.color1 %>"></i></button><span><%= @color.color1 %></span><br>
		<button class="btn" data-clipboard-text="<%= @color.color2 %>" ><i class="ion-waterdrop color-drop" style="color: <%= @color.color2 %>"></i></button><span><%= @color.color2 %></span><br>
		<button class="btn" data-clipboard-text="<%= @color.color3 %>" ><i class="ion-waterdrop color-drop" style="color: <%= @color.color3 %>"></i></button><span><%= @color.color3 %></span><br>

		<ul class="list">
			<li>
				<%= link_to vote_up_color_path(@color), class: "likes" do %>
					<i class="icon ion-heart"></i> <%= @color.votes_for %>
				<% end %>				
			</li>
			<li><a href="https://www.facebook.com/sharer.php?u=http://coolors.wagnerrosa.com/colors/<%= @color.id %>" class="share"><i class="icon ion-social-facebook"></i>Share</a></li>
			<li><a href="https://twitter.com/intent/tweet?url=http://coolors.wagnerrosa.com/colors/<%= @color.id %>" class="tweet"><i class="icon ion-social-twitter"></i>Tweet</a></li>
		</ul>		
	</div>

	<% if user_signed_in? %>
		<% if current_user.admin? %>
		<div class="admin-area clearfix">
			<%= link_to "Edit", edit_color_path(@color) %>
			<%= link_to "Delete", color_path(@color), method: :delete, data: { confirm: "Are you sure you want to delete this cool color?"} %>			
		</div>
		<% end %>
	<% end %>
</div>	
<%= javascript_tag do %>
	var clipboard = new Clipboard('.btn');
	clipboard.on('success', function(e) {
	console.log(e);
	});
	clipboard.on('error', function(e) {
	console.log(e);
	});
<% end %>

app/views/colors/trend.html.erb
<div id="colors-wrapper" class="row">

	<div class="menu-options clearfix">
		<ul class="col-xs-12">
			<li>
				<%= link_to "latest", root_path, class: "latest" %>
			</li>
			<li>
				<%= link_to "trends", colors_trend_path, class: "trend active" %>
			</li>
		</ul>
	</div>

<% @colors.each do |color| %>
	<div id="color-<%= color.id %>" class="col-xs-12 col-sm-6 col-md-4 col-lg-3 box-color">
		<button class="btn" data-clipboard-text="<%= color.color1 %>" ><i class="ion-waterdrop color-drop" style="color: <%= color.color1 %>"></i></button><br>
		<button class="btn" data-clipboard-text="<%= color.color2 %>" ><i class="ion-waterdrop color-drop" style="color: <%= color.color2 %>"></i></button><br>
		<button class="btn" data-clipboard-text="<%= color.color3 %>" ><i class="ion-waterdrop color-drop" style="color: <%= color.color3 %>"></i></button><br>		

		<ul class="list">
			<li>
				<%= link_to vote_up_color_path(color), class: "likes" do %>
					<i class="icon ion-heart"></i><%= color.votes_for %>
				<% end %>				
			</li>
			<li><%= link_to 'Show Coolor', color, :class => "show" %></li>
		</ul>
		
	</div>
<% end %>
</div>

<%= javascript_tag do %>
	var clipboard = new Clipboard('.btn');
	clipboard.on('success', function(e) {
	console.log(e);
	});
	clipboard.on('error', function(e) {
	console.log(e);
	});
<% end %>

app/views/layouts/_footer.erb
<%# app/views/layouts/_footer.erb %>

<footer class="clearfix">
	<div class="button-footer">
		<a href="https://github.com/wagnerrosa/coolors" target="_blank" class="button-footer"><i class="icon ion-social-github"></i>Source code</a>
	</div>	
	<div class="lx clearfix">
		<a id="footer#electrico" href="http://wagnerrosa.com" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="37.6766mm" height="27.0932mm" version="1.1" style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd"
		viewBox="0 0 3768 2709"
		xmlns:xlink="http://www.w3.org/1999/xlink">
		<defs>
		<style type="text/css">
		<![CDATA[
		.str6 {stroke:black;stroke-width:33.86}
		.str7 {stroke:#90551B;stroke-width:33.86}
		.str1 {stroke:black;stroke-width:67.73}
		.str2 {stroke:black;stroke-width:42.33}
		.str4 {stroke:black;stroke-width:42.33}
		.str8 {stroke:#4F4C43;stroke-width:42.33}
		.str5 {stroke:#90551B;stroke-width:42.33}
		.str3 {stroke:black;stroke-width:20}
		.str0 {stroke:#DCDFE0;stroke-width:20}
		.fil10 {fill:none}
		.fil6 {fill:black}
		.fil5 {fill:#1B3B50}
		.fil9 {fill:#1B3B50}
		.fil7 {fill:#282327}
		.fil1 {fill:#282327}
		.fil4 {fill:#716559}
		.fil8 {fill:#7A412D}
		.fil0 {fill:#DCDFE0}
		.fil3 {fill:#EBECE7}
		.fil2 {fill:#F2B121}
		.fil11 {fill:black;fill-rule:nonzero}
		]]>
		</style>
		</defs>
		<g id="Camada_x0020_1">
		<metadata id="CorelCorpID_0Corel-Layer"/>
		<g id="_303585416">
		<rect class="fil0 str0" x="13" y="2431" width="3742" height="265" rx="132" ry="132"/>
		<polygon class="fil1 str1" points="3440,2277 3440,2277 3620,2466 3550,2489 "/>
		<polygon class="fil1 str2" points="338,2277 338,2277 157,2466 227,2489 "/>
		<rect class="fil2 str2" id="bondinho" x="236" y="1651" width="3359" height="648"/>
		<rect class="fil3 str3" x="236" y="1155" width="3359" height="496"/>
		<path class="fil4 str4" d="M196 1151l3438 0 0 -116c0,-65 -52,-117 -116,-117l-3205 0c-64,0 -117,52 -117,117l0 116z"/>
		<path class="fil5 str5" d="M1111 1736l396 0 0 -420c0,-30 -25,-56 -56,-56l-284 0c-31,0 -56,26 -56,56l0 420z"/>
		<rect class="fil5 str5" x="1112" y="1455" width="397" height="282"/>
		<rect class="fil4 str4" x="1310" y="756" width="1210" height="162"/>
		<rect class="fil6 str3" x="940" y="2150" width="2048" height="149"/>
		<circle class="fil7 str6" cx="1237" cy="2401" r="198"/>
		<path class="fil5 str5" d="M232 1251l98 0c54,0 98,45 98,99l0 391 -196 0 0 -490z"/>
		<path class="fil1 str2" d="M971 2150l1916 0 0 38c0,20 -17,38 -38,38l-1840 0c-21,0 -38,-18 -38,-38l0 -38z"/>
		<circle class="fil6" cx="1237" cy="2401" r="138"/>
		<circle class="fil1" cx="1237" cy="2401" r="69"/>
		<circle class="fil7 str6" cx="2507" cy="2401" r="198"/>
		<circle class="fil6" cx="2507" cy="2401" r="138"/>
		<circle class="fil1" cx="2507" cy="2401" r="69"/>
		<path class="fil1 str2" d="M848 2298l2162 0 0 41c0,23 -18,42 -41,42l-2080 0c-23,0 -41,-19 -41,-42l0 -41z"/>
		<path class="fil1 str2" d="M971 2448l1916 0 0 39c0,21 -17,38 -38,38l-1840 0c-21,0 -38,-17 -38,-38l0 -39z"/>
		<path class="fil8 str2" d="M236 2150l740 0 0 74c0,41 -33,75 -74,75l-666 0 0 -149z"/>
		<path class="fil8 str2" d="M3594 2150l-783 0 0 74c0,41 33,75 74,75l709 0 0 -149z"/>
		<path class="fil4 str4" d="M366 1027l140 0 0 -125c0,-39 -31,-70 -70,-70l-70 0 0 195z"/>
		<path class="fil4 str4" d="M3462 1027l-141 0 0 -125c0,-39 32,-70 71,-70l70 0 0 195z"/>
		<path class="fil5 str7" d="M3601 1251l-99 0c-54,0 -98,45 -98,99l0 391 197 0 0 -490z"/>
		<rect class="fil9" x="814" y="1298" width="105" height="318" rx="36" ry="43"/>
		<rect class="fil9" x="814" y="1704" width="105" height="339" rx="36" ry="46"/>
		<line class="fil10 str8" x1="755" y1="1257" x2="755" y2= "2129" />
		<g>
		<path class="fil11" d="M3151 101l-615 749 -32 -26 615 -749 32 26zm70 57l-14 16 -171 -140 27 -32 171 140 -13 16z"/>
		</g>
		<g id="_303587792">
		<path class="fil5 str5" d="M1716 1736l397 0 0 -420c0,-30 -25,-56 -56,-56l-285 0c-31,0 -56,26 -56,56l0 420z"/>
		<rect class="fil5 str5" x="1717" y="1455" width="397" height="282"/>
		</g>
		<path class="fil5 str5" d="M2375 1736l397 0 0 -420c0,-30 -25,-56 -56,-56l-284 0c-31,0 -57,26 -57,56l0 420z"/>
		<rect class="fil5 str5" x="2377" y="1455" width="397" height="282"/>
		<rect class="fil10 str4" x="541" y="1253" width="427" height="896"/>
		<rect class="fil9" x="594" y="1298" width="105" height="318" rx="36" ry="43"/>
		<rect class="fil9" x="594" y="1704" width="105" height="339" rx="36" ry="46"/>
		<rect class="fil9" x="3151" y="1298" width="105" height="318" rx="36" ry="43"/>
		<rect class="fil9" x="3151" y="1704" width="105" height="339" rx="36" ry="46"/>
		<line class="fil10 str8" x1="3092" y1="1257" x2="3092" y2= "2129" />
		<rect class="fil10 str4" x="2879" y="1253" width="427" height="896"/>
		<rect class="fil9" x="2932" y="1298" width="105" height="318" rx="36" ry="43"/>
		<rect class="fil9" x="2932" y="1704" width="105" height="339" rx="36" ry="46"/>
		</g>
		</g>
		</svg></a>
		<div class="text-footer">
			<p>Built with <i class="iconico ion-heart"></i> in<br>Lisbon by <a target="_blank" id="footer#wagnerrosa" href="http://wagnerrosa.com">Wagner Rosa</a></p>
			<span>© 2016, Coolors.</span>							
		</div>
	</div>

</footer>

app/views/layouts/_header.erb
<%# app/views/layouts/_header.erb %>

<header class="header">
	<%= link_to root_path, :class => "logo" do %>
		<h1>Coolors</h1> 
	<% end %>	
</header>

<div class="submenu clearfix">
	<nav>
		<p class="instruction">Click on the drop to copy the Coolor!</p>
		<% if user_signed_in? %>
		<%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => "button signout" %>
			<% if current_user.admin? %>
				<span class="button admin-advice"><i class="icon ion-gear-a"></i>Admin Logged!</span>		
			<% end %>
		<% end %>
		<%= link_to new_color_path, :class => "button" do %>
			<i class="icon ion-plus-circled"></i>
			New Coolors
		<% end %>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
 	<title>Coolors</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag 'application', 'https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' %>

</head>
<body>
	<div class="container">

		<% if notice %>
		   <div class="advice"><p class="notice"><%= notice %></p></div>
		<% elsif notice %>
		   <div class="advice"><p class="alert"><%= alert %></p></div>
		<% end %>
		<%= render 'layouts/header' %>
		


		<main>
			
			<%= yield %>
		</main>
			
		<%= render 'layouts/footer' %>

	</div>
</body>
</html>